### ISSUE TITLE
[Request] Newer versions

### ISSUE THREAD

**Issue by SettingDust** [natanfudge/Fabric-Drawer#2]
eg. 1.18, 1.19 

- [ ] 1.18.2 #3

**Comment by natanfudge** [comment]
Try [Silk](https://silkmc.net/silk/docs/),
Can you describe why you use fabric drawer over Silk for 1.18+?

**Comment by SettingDust** [comment]
IDK. There isn't silk on fabric wiki. What I find for serialization is drawer XDDD. ~~Wasting time, sadly :(~~

**Comment by SettingDust** [comment]
Well, silk don't have nbt serializers. Only a format. Have to add serializers manually

**Comment by natanfudge** [comment]
![Screenshot_2022-09-26-15-06-23-19_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://user-images.githubusercontent.com/25990014/192272144-4adcb80b-1e5e-45c4-9b82-c71446e6aa6d.jpg)
What do you mean?

**Comment by SettingDust** [comment]
> ![Screenshot_2022-09-26-15-06-23-19_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://user-images.githubusercontent.com/25990014/192272144-4adcb80b-1e5e-45c4-9b82-c71446e6aa6d.jpg) What do you mean?

Only a serial format. No serializers. The serializers is planned

**Comment by SettingDust** [comment]
For ones want to find a higher version nbt serialization. The serializers of silk are WIP. But there is no active 1.18.2 version for silk. I'll backport the changes on my fork. https://github.com/SettingDust/silk/tree/1.18.2
https://github.com/SilkMC/silk/pull/40
https://github.com/SilkMC/silk/pull/39

**Comment by SettingDust** [comment]
Writing my own lib finally https://github.com/SettingDust/minecraft-tag-serialization.
Silk seems won't accept the pr

**Comment by natanfudge** [comment]
@SettingDust You may be interested in the fact Fabric Drawer (now called kotlin-serialization-minecraft) has been improved and updated to Minecraft 1.19.2.
